spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: product_db
server:
  port: 8087
  
---
spring:
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      authentication-database: admin
      username: productadmin
      password: password
---

spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      port: 27019